package org.teamsai.saibackend.domain.notification.type;

public enum NotificationType {
    SETTLEMENT_PARTICIPANT_ADDED,
    CONTRACT_REQUESTED,
    CONTRACT_CHANGE,
    BANK_TRANSACTION_MATCHING_REVIEW,
    REPAYMENT_DUE_REMINDER_D3,
    REPAYMENT_DUE_REMINDER_D1,
    REPAYMENT_DUE_REMINDER_DDAY,
    SETTLEMENT_DUE_REMINDER_D3,
    SETTLEMENT_DUE_REMINDER_D1,
    SETTLEMENT_DUE_REMINDER_DDAY
}
